Publish to conda
openfisca/extension-template pull request #43
Opened 2022-02-15 16:37 UTC by benoit-cty

* Technical improvement.
* Details:
  - Publish to conda in CI
  - Move CI from Circle CI to Github Action as it is the case for others OpenFisca projects

- - - -

These changes change non-functional parts of this repository : CI.

2022-02-17 15:17 UTC, benoit-cty commented
Run OK for conda : https://github.com/openfisca/extension-template/actions/runs/1859207665

2022-04-07 07:55 UTC, sandcha commented
Hello @benoit-cty, Thank you for this new feature(s)!
This PR does more than publishing to conda, it also migrates the CI checks from CircleCI to GitHub Actions. Could you explicit why you made this choice? And the list of credentials/rights to activate on this repository? 🙂

2022-04-07 14:27 UTC, benoit-cty commented
I move CI from Circle CI to Github Action as it is the CI used for others OpenFisca projects.

2022-05-24 12:03 UTC, sandcha requested changes
Thank you @benoit-cty for this new conda installation! Tested and it woks 🙌 
The main request here is:
* remove the old circleci configuration as we are migrating the CI to GitHub Action here,
* fix some typo.

2022-05-24 12:03 UTC, sandcha commented on .conda/README.md
> +There is two way of publishing to conda:
The documentation is similar to [conda documentation](https://github.com/openfisca/openfisca-core/pull/1105) in `openfisca-core`. You might find some similar comments/this review not entirely original 😅 
```suggestion
There are two ways of publishing to conda:

```

2022-05-24 12:03 UTC, sandcha commented on .conda/README.md
> +- A fully automatic in CI that publish to an "openfisca" channel. See below for more information.
Typo and standardization of style:
```suggestion
- A fully automatic in CI that publishes to an `openfisca` channel. See below for more information.

```

2022-05-24 12:03 UTC, sandcha commented on .conda/README.md
> +- A more complex for Conda-Forge.
> Add link to help the reader and remove any ambiguity?
```suggestion
- A more complex for [Conda-Forge](https://conda-forge.org).

```

2022-05-24 12:03 UTC, sandcha commented on .conda/README.md
> +We use both for openfisca-core but only _openfisca channel_ for _extension-template_.
> Minor suggestion:
```suggestion
We use both for openfisca-core but only `openfisca` channel for `extension-template`.

```

2022-05-24 12:03 UTC, sandcha commented on .conda/README.md
> +The CI automaticaly upload the PyPi package, see the `.github/workflow.yml`, step `publish-to-conda`.
Explicit which package as the next steps will depend on it?
```suggestion
The CI automaticaly upload the [PyPi package](https://pypi.org/project/OpenFisca-Extension-Template/), see the `.github/workflow.yml`, step `publish-to-conda`.

```

2022-05-24 12:03 UTC, sandcha commented on .conda/README.md
> +- Create a token on https://anaconda.org/openfisca/settings/access with _Allow write access to the API site_. Warning, it expire on 2023/01/13.
> Optional; I might be partial to italic because I don't see it/in my case, it doesn't highlight the information 😳 
```suggestion
- Create a token on https://anaconda.org/openfisca/settings/access with `Allow write access to the API site`. Warning, it expire on 2023/01/13.

```

2022-05-24 12:03 UTC, sandcha commented on .conda/README.md
> +- Create a token on https://anaconda.org/openfisca/settings/access with _Allow write access to the API site_. Warning, it expire on 2023/01/13.
Typo:
```suggestion
- Create a token on https://anaconda.org/openfisca/settings/access with _Allow write access to the API site_. Warning, it expires on 2023/01/13.

```

2022-05-24 12:03 UTC, sandcha commented on .conda/README.md
> +## Manual actions made to make it works the first time
We might not understand "what should work". Use same title than in openfisca-core documentation?
```suggestion
## Manual actions for first time publishing

```

2022-05-24 12:03 UTC, sandcha commented on .conda/README.md
> +- Put the token in a CI env variable ANACONDA_TOKEN.
Use fully explicit description?
```suggestion
- Put the token in a CI environment variable named `ANACONDA_TOKEN`.

```

2022-05-24 12:03 UTC, sandcha commented on .conda/README.md
> +## Manual actions before CI exist
Typo (exists) but even if the CI script existed, it's to add some step in it, isn't it? Use openfisca-core's documentation title?
```suggestion
## Manual actions before CI configuration

```

2022-05-24 12:03 UTC, sandcha commented on .conda/meta.yaml
> +  home: https://fr.openfisca.org/
Set a link to a website shared by all countries as `extension-template` is an international module?
```suggestion
  home: https://openfisca.org
```

2022-05-24 12:03 UTC, sandcha commented on .conda/meta.yaml
> +  summary: "OpenFisca tax and benefit system for extension-Template."
Use repository description ([here on the top left side](https://github.com/openfisca/extension-template)) as the rules in the extension does not stand by themselves (they need the entities defined in a tax benefit system)? 
```suggestion
  summary: "Template to build extensions to an existing OpenFisca country package."
```

2022-05-24 12:03 UTC, sandcha commented on .conda/meta.yaml
> +    This repository contains the E  xtension-Template module, to work with OpenFisca.
Minor typo:
```suggestion
    This repository contains the Extension-Template module, to work with OpenFisca.
```

2022-05-24 12:03 UTC, sandcha commented on .conda/meta.yaml
> +  doc_url: https://fr.openfisca.org/
Use the link to the official documentation or to repository README file?
```suggestion
  doc_url: https://openfisca.org/doc
```
or : 
```suggestion
  doc_url: https://github.com/openfisca/extension-template#openfisca-extension-template
```

2022-05-24 12:03 UTC, sandcha commented on .github/get_pypi_info.py
> +"""Script to get information needed by .conda/meta.yaml from PyPi JSON API.
> Already reviewed in openfisca-france ([PR 1786](https://github.com/openfisca/openfisca-france/pull/1786/files#diff-a275384346a87e254bc35c3ff8bd80d795e105b453e9e8e0c2f0ca815d0cd9c0))

2022-05-24 12:03 UTC, sandcha commented on .github/get_pypi_info.py
> +        if v["packagetype"] == "sdist":  # for .tag.gz
Typo:
```suggestion
        if v["packagetype"] == "sdist":  # for .tar.gz

```

2022-05-24 12:03 UTC, sandcha commented on .github/has-functional-changes.sh
> +#! /usr/bin/env bash
> Copied from `.circleci/has-functional-changes.sh`

2022-05-24 12:03 UTC, sandcha commented on .github/is-version-number-acceptable.sh
> +#! /usr/bin/env bash
> Copied from `.circleci/is-version-number-acceptable.sh`

2022-05-24 12:03 UTC, sandcha commented on .github/publish-git-tag.sh
> +#! /usr/bin/env bash
> Copied from `.circleci/publish-git-tag.sh`

2022-05-24 12:03 UTC, sandcha commented on .github/workflows/workflow.yml
> +        uses: actions/setup-python@v2
> For all concerned jobs, isn't it v3 now according to [setup-python documentation](https://github.com/actions/setup-python#usage)? 🤔

2022-05-24 12:03 UTC, sandcha commented on .github/workflows/workflow.yml
> +        uses: actions/checkout@v2
> For all concerned jobs, isn't it v3 now according to GitHub Actions [checkout documentation](https://github.com/actions/checkout#usage)? 🤔

2022-05-24 12:03 UTC, sandcha commented on .github/workflows/workflow.yml
> +        uses: actions/cache@v2
> cache also [exists as v3](https://github.com/actions/cache#v3).

2022-05-24 12:03 UTC, sandcha commented on .github/workflows/workflow.yml
> +      - uses: conda-incubator/setup-miniconda@v2
👍

2022-05-24 12:03 UTC, sandcha commented on .github/workflows/workflow.yml
> +          python-version: "3.7.9"
Is `.9` here to explicit that with miniconda, we wouldn't get a `3.7.12` or is it a typo? 
> We can also set it to `3.7` if it allows for automatic update of the patch revision.

2022-05-24 12:03 UTC, sandcha commented on CHANGELOG.md
> +  - Add publish to conda in CI.
Typo ?
```suggestion
  - Add publishing to conda in CI.
```

2022-05-24 12:03 UTC, sandcha commented on README.md
> +### Installing with pew
`pew` and `conda` don't provide the same services. Use tools that could be compared in the installation titles?
For example: 
```suggestion
### Installing with pip and pew
```

2022-05-24 12:03 UTC, sandcha commented on README.md
> +Conda is the easiest way to use OpenFisca under Windows as by installing Anaconda you will get:
Just after `## Installing` section, add a sentence to help the user chose between the installation options? Use a part of the sentence above?

```
## Installing

[conda](https://docs.conda.io) is the easiest way to use OpenFisca under Windows.
On other OS systems, the default installation is based on [pip](https://pip.pypa.io/en/stable/) Python package installer. 
```

2022-05-24 12:03 UTC, sandcha commented on README.md
> +If you are familiar with command line you could use [Miniconda](https://docs.conda.io/projects/conda/en/latest/user-guide/install/windows.html), wich need very much less disk space than Anaconda.
```suggestion
If you are familiar with command line you could use [Miniconda](https://docs.conda.io/projects/conda/en/latest/user-guide/install/windows.html), which needs very much less disk space than Anaconda.
```

2022-05-24 12:03 UTC, sandcha commented on README.md
> +For informations on how we publish to conda-forge, see [README](.conda/README.md).
> Suggestion:
```suggestion
For informations on how we publish to [conda-forge](https://conda-forge.org), see [README](.conda/README.md).
```

2022-05-24 12:03 UTC, sandcha commented on README.md
> +If you are familiar with command line you could use [Miniconda](https://docs.conda.io/projects/conda/en/latest/user-guide/install/windows.html), wich need very much less disk space than Anaconda.
Add explicit that the commands given above will then work in a shell terminal?

2022-05-24 12:03 UTC, sandcha commented on README.md
> +- `conda create --name openfisca-ext-tplt python=3.7` to create an openfisca environment.
```suggestion
- `conda create --name openfisca-ext-tplt python=3.7` to create an `openfisca-ext-tplt` virtual environment.
```

2022-05-24 12:03 UTC, sandcha commented on README.md
> +- `conda install -c openfisca openfisca-extension-template` to install the package and all dependencies.
👍 Tested without error on local environment by following these steps and then, running `openfisca test openfisca_extension_template/tests/local_benefit.yaml -e openfisca_extension_template`.

2022-05-24 12:03 UTC, sandcha commented on .github/has-functional-changes.sh
> +#! /usr/bin/env bash
As we are deciding to move from `CircleCI` continuous integration system to `GitHub Actions`, remove the deprecated `.circleci` (renamed to `.disable-circleci`) directory and all content/references?

2022-05-24 12:06 UTC, sandcha commented
@benoit-cty Juste a reminder to us both: upon this PR merge, we will need to update this repository settings to remove the circleci check. 🙂

2022-12-12 08:27 UTC, MattiSG commented
Following #51, the Github Actions migration has been handled. This changeset can (and should) thus be updated to remove that part 🙂

2024-10-24 11:06 UTC, benoit-cty commented
Closing this PR as there has been many changes in the repo and nothing is relevant now.

2024-10-24 11:06 UTC, closed without merging